/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { appModelsList } from "../../funcs/appModelsList.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$appModelsList: ToolDefinition = {
  name: "app-models-list",
  description: `Get Models

Get the list of available ai models.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await appModelsList(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
