/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { appsList } from "../../funcs/appsList.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$appsList: ToolDefinition = {
  name: "apps-list",
  description: `List All Apps`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await appsList(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
