/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { completionsPost } from "../../funcs/completionsPost.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.CompletionRequest$inboundSchema,
};

export const tool$completionsPost: ToolDefinition<typeof args> = {
  name: "completions-post",
  description: `Post Completions

Post a completion request to the ai model.

Returns:

    - StreamingResponse when request.stream=True

    - CompletionResponse when request.stream=False`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await completionsPost(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
