/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { HatzAICore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope, mcpScopes } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$appModelsList } from "./tools/appModelsList.js";
import { tool$appsGetById } from "./tools/appsGetById.js";
import { tool$appsList } from "./tools/appsList.js";
import { tool$appsQuery } from "./tools/appsQuery.js";
import { tool$completionsPost } from "./tools/completionsPost.js";
import { tool$filesList } from "./tools/filesList.js";
import { tool$filesUpload } from "./tools/filesUpload.js";
import { tool$modelsList } from "./tools/modelsList.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  apiKeyHeader?: SDKOptions["apiKeyHeader"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "HatzAI",
    version: "0.2.0",
  });

  const client = new HatzAICore({
    apiKeyHeader: deps.apiKeyHeader,
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
  });

  const scopes = new Set(deps.scopes ?? mcpScopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const register = { tool, resource, resourceTemplate };
  void register; // suppress unused warnings

  tool(tool$modelsList);
  tool(tool$completionsPost);
  tool(tool$filesUpload);
  tool(tool$filesList);
  tool(tool$appModelsList);
  tool(tool$appsList);
  tool(tool$appsGetById);
  tool(tool$appsQuery);

  return server;
}
