/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { completionsPost } from "../funcs/completionsPost.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Completions extends ClientSDK {
  /**
   * Post Completions
   *
   * @remarks
   * Post a completion request to the ai model.
   *
   * Returns:
   *
   *     - StreamingResponse when request.stream=True
   *
   *     - CompletionResponse when request.stream=False
   */
  async post(
    request: components.CompletionRequest,
    options?: RequestOptions,
  ): Promise<
    operations.PostCompletionsV1ChatCompletionsPostResponsePostCompletionsV1ChatCompletionsPost
  > {
    return unwrapAsync(completionsPost(
      this,
      request,
      options,
    ));
  }
}
