/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filesList } from "../funcs/filesList.js";
import { filesUpload } from "../funcs/filesUpload.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Files extends ClientSDK {
  /**
   * Upload File
   */
  async upload(
    request: components.BodyUploadFileV1FilesUploadPost,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(filesUpload(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Files
   */
  async list(
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(filesList(
      this,
      options,
    ));
  }
}
