/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { AppModels } from "./appmodels.js";
import { Apps } from "./apps.js";
import { Completions } from "./completions.js";
import { Files } from "./files.js";
import { Models } from "./models.js";

export class HatzAI extends ClientSDK {
  private _models?: Models;
  get models(): Models {
    return (this._models ??= new Models(this._options));
  }

  private _completions?: Completions;
  get completions(): Completions {
    return (this._completions ??= new Completions(this._options));
  }

  private _files?: Files;
  get files(): Files {
    return (this._files ??= new Files(this._options));
  }

  private _appModels?: AppModels;
  get appModels(): AppModels {
    return (this._appModels ??= new AppModels(this._options));
  }

  private _apps?: Apps;
  get apps(): Apps {
    return (this._apps ??= new Apps(this._options));
  }
}
