workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Hatz API:
        inputs:
            - location: ../hatz-api/openapi_spec.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/hatz-ai/general/hatz-api
targets:
    hatz-ai:
        target: typescript
        source: Hatz API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/hatz-ai/general/hatz-api-typescript-code-samples
            blocking: false
