/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type QueryAppV1AppAppIdQueryPostRequest = {
  /**
   * The unique identifier of the app to query
   */
  appId: string;
  appQueryRequest: components.AppQueryRequest;
};

/**
 * Successful Response
 */
export type QueryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPost =
  | components.CompletionsStreamingResponse
  | components.CompletionResponse;

/** @internal */
export const QueryAppV1AppAppIdQueryPostRequest$inboundSchema: z.ZodType<
  QueryAppV1AppAppIdQueryPostRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  app_id: z.string(),
  AppQueryRequest: components.AppQueryRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "app_id": "appId",
    "AppQueryRequest": "appQueryRequest",
  });
});

/** @internal */
export type QueryAppV1AppAppIdQueryPostRequest$Outbound = {
  app_id: string;
  AppQueryRequest: components.AppQueryRequest$Outbound;
};

/** @internal */
export const QueryAppV1AppAppIdQueryPostRequest$outboundSchema: z.ZodType<
  QueryAppV1AppAppIdQueryPostRequest$Outbound,
  z.ZodTypeDef,
  QueryAppV1AppAppIdQueryPostRequest
> = z.object({
  appId: z.string(),
  appQueryRequest: components.AppQueryRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    appId: "app_id",
    appQueryRequest: "AppQueryRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QueryAppV1AppAppIdQueryPostRequest$ {
  /** @deprecated use `QueryAppV1AppAppIdQueryPostRequest$inboundSchema` instead. */
  export const inboundSchema = QueryAppV1AppAppIdQueryPostRequest$inboundSchema;
  /** @deprecated use `QueryAppV1AppAppIdQueryPostRequest$outboundSchema` instead. */
  export const outboundSchema =
    QueryAppV1AppAppIdQueryPostRequest$outboundSchema;
  /** @deprecated use `QueryAppV1AppAppIdQueryPostRequest$Outbound` instead. */
  export type Outbound = QueryAppV1AppAppIdQueryPostRequest$Outbound;
}

export function queryAppV1AppAppIdQueryPostRequestToJSON(
  queryAppV1AppAppIdQueryPostRequest: QueryAppV1AppAppIdQueryPostRequest,
): string {
  return JSON.stringify(
    QueryAppV1AppAppIdQueryPostRequest$outboundSchema.parse(
      queryAppV1AppAppIdQueryPostRequest,
    ),
  );
}

export function queryAppV1AppAppIdQueryPostRequestFromJSON(
  jsonString: string,
): SafeParseResult<QueryAppV1AppAppIdQueryPostRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      QueryAppV1AppAppIdQueryPostRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryAppV1AppAppIdQueryPostRequest' from JSON`,
  );
}

/** @internal */
export const QueryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPost$inboundSchema:
  z.ZodType<
    QueryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPost,
    z.ZodTypeDef,
    unknown
  > = z.union([
    components.CompletionsStreamingResponse$inboundSchema,
    components.CompletionResponse$inboundSchema,
  ]);

/** @internal */
export type QueryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPost$Outbound =
  | components.CompletionsStreamingResponse$Outbound
  | components.CompletionResponse$Outbound;

/** @internal */
export const QueryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPost$outboundSchema:
  z.ZodType<
    QueryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPost$Outbound,
    z.ZodTypeDef,
    QueryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPost
  > = z.union([
    components.CompletionsStreamingResponse$outboundSchema,
    components.CompletionResponse$outboundSchema,
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QueryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPost$ {
  /** @deprecated use `QueryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPost$inboundSchema` instead. */
  export const inboundSchema =
    QueryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPost$inboundSchema;
  /** @deprecated use `QueryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPost$outboundSchema` instead. */
  export const outboundSchema =
    QueryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPost$outboundSchema;
  /** @deprecated use `QueryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPost$Outbound` instead. */
  export type Outbound =
    QueryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPost$Outbound;
}

export function queryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPostToJSON(
  queryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPost:
    QueryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPost,
): string {
  return JSON.stringify(
    QueryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPost$outboundSchema
      .parse(queryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPost),
  );
}

export function queryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPostFromJSON(
  jsonString: string,
): SafeParseResult<
  QueryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPost,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      QueryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPost$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'QueryAppV1AppAppIdQueryPostResponseQueryAppV1AppAppIdQueryPost' from JSON`,
  );
}
