/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PromptSection = {
  body: string;
  position: number;
};

/** @internal */
export const PromptSection$inboundSchema: z.ZodType<
  PromptSection,
  z.ZodTypeDef,
  unknown
> = z.object({
  body: z.string(),
  position: z.number().int(),
});

/** @internal */
export type PromptSection$Outbound = {
  body: string;
  position: number;
};

/** @internal */
export const PromptSection$outboundSchema: z.ZodType<
  PromptSection$Outbound,
  z.ZodTypeDef,
  PromptSection
> = z.object({
  body: z.string(),
  position: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PromptSection$ {
  /** @deprecated use `PromptSection$inboundSchema` instead. */
  export const inboundSchema = PromptSection$inboundSchema;
  /** @deprecated use `PromptSection$outboundSchema` instead. */
  export const outboundSchema = PromptSection$outboundSchema;
  /** @deprecated use `PromptSection$Outbound` instead. */
  export type Outbound = PromptSection$Outbound;
}

export function promptSectionToJSON(promptSection: PromptSection): string {
  return JSON.stringify(PromptSection$outboundSchema.parse(promptSection));
}

export function promptSectionFromJSON(
  jsonString: string,
): SafeParseResult<PromptSection, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PromptSection$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PromptSection' from JSON`,
  );
}
